# Site settings
name: Ekansh Gupta
title: Ekansh Gupta | Mecahnical Engineer
description: Design-minded front-end software engineer focused on building beautiful interfaces and experiences
url: https://bchiang7.github.io/
baseurl: ''
email: ekanshgupta92@gmail.com
cover: https://ekanshgupta.github.io/img/og.png
logo: https://ekanshgupta.github.io/img/emojis/technologist.png
resume: https://ekanshgupta.github.io/resume.pdf
social:
  - title: email
    url: mailto:ekanshgupta92@gmail.com
  - title: instagram
    url: https://instagram.com/ekanshgupta92
  - title: github
    url: https://github.com/ekanshgupta92
  - title: linkedin
    url: https://www.linkedin.com/in/ekansh-gupta-1a22461aa/

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
